### ISSUE TITLE
Roadmap: v5

### ISSUE THREAD

**Issue by mskocik** [mskocik/svelecte#259]
- [x] update dependencies (svelte, vite, vitest)
- [x] rewrite reactivity to runes
- [x] #249 
- [x] #230 (?)
- [x] polish tests and make sure everything works
- [x] #266 
- [x] #267
- [ ] improve documentation (more examples - rendering, positionResolver, snippet with highlightSearch)
  - [ ] item creation could be on separate page
- [ ] make web responsive
- [x] and... ?

**Comment by mskocik** [comment]
Update docs... maybe later 😝
